server:
  port: 9084
  
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gothamaha/config-server-spring-boot-apps
          clone-on-start: true